name: CI and Create Release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm ci
      - run: npm test

      # Automatically bump version and create git tag
      - name: Bump version and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # You can replace "patch" with "minor" or "major" if needed
          npm version patch -m "chore(release): %s [skip ci]"
          git push origin main --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Create GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.READ_WRITE_GITHUB_TOKEN  }}
